### ISSUE TITLE
Add description of algorithm detail

### ISSUE THREAD

**Issue by suma** [jubatus/website#18]
Recover [method.rst](https://github.com/jubatus/website/blob/00b90b35d4716cfe88bb79e273e179d32ca98144/source/ja/method.rst) which removed e76c51fab058464f7755cf2ca897a22da1d3a833 and add more `method`'s algorithm description.

---
- PA(PA, PA1, PA2): Passive Aggressive
  - Koby Crammer, Ofer Dekel, Shai Shalev-Shwartz and Yoram Singer, Online Passive-Aggressive Al- gorithms, Proceedings of the Sixteenth Annual Conference on Neural Information Processing Systems (NIPS), 2003.
  - Koby Crammer, Ofer Dekel, Joseph Keshet, Shai Shalev-Shwartz, Yoram Singer, Online Passive- Aggressive Algorithms. Journal of Machine Learning Research, 2006.
  - Koby Crammer and Yoram Singer. Ultraconservative online algorithms for multiclass problems. Journal of Machine Learning Research, 2003.
- CW:  Confidence Weighted Learning
  - MarkDredze,KobyCrammerandFernandoPereira,Confidence-WeightedLinearClassification,Proceed- ings of the 25th International Conference on Machine Learning (ICML), 2008
  - Koby Crammer, Mark Dredze and Fernando Pereira, Exact Convex Confidence-Weighted Learning, Pro- ceedings of the Twenty Second Annual Conference on Neural Information Processing Systems (NIPS), 2008
  - KobyCrammer,MarkDredzeandAlexKulesza,Multi-ClassConfidenceWeightedAlgorithms,Empirical Methods in Natural Language Processing (EMNLP), 2009
- AROW: Adaptive Regularization of Weight vectors
  - Koby Crammer, Alex Kulesza and Mark Dredze, Adaptive Regularization Of Weight Vectors, Advances in Neural Information Processing Systems, 2009
- NHERD: Normal Herd
  - Koby Crammer and Daniel D. Lee, Learning via Gaussian Herding, Neural Information Processing Systems (NIPS), 2010.

**Comment by rimms** [comment]
* Bandit: https://qiita.com/TkrUdagawa/items/530efb856449fc6b7907
