### ISSUE TITLE
classifier algorithm list is a bit ugly

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/website#185]
https://github.com/jubatus/website/pull/175#discussion-diff-25058283L103

NHERD/NN is inproperly indented.
http://jubat.us/ja/api_classifier.html
http://jubat.us/en/api_classifier.html

**Comment by gintenlabo** [comment]
Already fixed via https://github.com/jubatus/website/commit/0d80f98247fe4d663682da8ab03b7688ef4d0e6c.

**Comment by kmaehashi** [comment]
Thanks!

I confirmed that this problem does not exist anymore.
http://ci.jubat.us/job/website/ws/Branch/develop/nightly/ja/api_classifier.html#configuration
