### ISSUE TITLE
Update sphinx theme using sphinx_rtd_theme

### ISSUE THREAD

**Issue by shiodat** [jubatus/website#283]
Using following theme, we can access table of contents anytime!
* sphinx_rtd_theme : https://github.com/snide/sphinx_rtd_theme

**Comment by kmaehashi** [comment]
@shiodat Could you please update README (requirements to build docs?)
https://github.com/jubatus/website#requirements

**Comment by kmaehashi** [comment]
Fixed via #287, #299
