### ISSUE TITLE
jubaconv config documentation

### ISSUE THREAD

**Issue by shiodat** [jubatus/website#294]
Using jubaconv with json data, we have to add slash `/` at the start of value of `key`.

* default config
``` 
"num_rules": [ "key": "name". "type": "num"} 
```
* jubaconv config with json data
```
"num_rules": [ "key": "/name". "type": "num"}
```
This issue occurs because jubatus converts json data using slash.
https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/fv_converter/json_converter.cpp#L96-L110

We should document it.

**Comment by kmaehashi** [comment]
Fixed via #296
