### ISSUE TITLE
The top page always redirects to the English page

### ISSUE THREAD

**Issue by torash** [jubatus/website#318]
[The top page of Jubatus website](https://jubat.us) always redirects visitors to [the English page](https://jubat.us/en).
The redirection target should be selected based on browser language.

**Comment by kmaehashi** [comment]
We need some JavaScript to redirect using browser preferences. http://qiita.com/shogo82148/items/548a6c9904eb19269f8c

**Comment by kmaehashi** [comment]
Fixed via #319
