### ISSUE TITLE
"How To Contribute" link is 404 Not Found

### ISSUE THREAD

**Issue by kazuki** [jubatus/website#329]
In https://github.com/jubatus/website/blob/master/CONTRIBUTING.md
Currently link to http://jubat.us/ja/howtocontribute.html but this url is 404.
http://jubat.us/ja/developers/howtocontribute.html is correct.

**Comment by kmaehashi** [comment]
Thank you for reporting.
`CONTRIBUTING.md` in jubatus and jubatus_core repos must be fixed too.

**Comment by rimms** [comment]
Website repository was fixed via https://github.com/jubatus/website/pull/331

**Comment by kmaehashi** [comment]
Fixed via: https://github.com/jubatus/jubatus/commit/78c3d6f27a2299a4b2c13ac9f4441fce8d06711d
https://github.com/jubatus/jubatus_core/commit/5fc7de3bfb7357cc6805eddd198068ae37bc5e3e
