### ISSUE TITLE
dead-link in anomaly tutorial

### ISSUE THREAD

**Issue by ytobe** [jubatus/website#342]
In the tutorial of anomaly python  ( http://jubat.us/ja/tutorial/anomaly_python.html ) , 
indicated as below

> 　methodで設定した異常検知アルゴリズムのパラメータを設定します。
>     今回は”lof”を利用するため、Recommender API に従ってパラメータを設定します。 

When click link ”Recommender API ” , jump to 404 page.

Not only python , but java and ruby .
And English-version as well .

**Comment by rimms** [comment]
Fixed via #345
