### ISSUE TITLE
typo kth_ignore_same_point in FAQ

### ISSUE THREAD

**Issue by ytobe** [jubatus/website#343]
in the FAQ of anomaly ( http://jubat.us/ja/tips_faqs/faq.html#faqs-anomaly-ja ) ,  written as below :

>     jubaanomalyのスコアが極端に大きな値を返却する
> 
>     ある一点の近傍に多数の点が集中しすぎると、 kth_ignore_same_point のオプションを付与しても、 anomalyのスコアが極端に大きくなる場合があります。 これは、floatでの数値計算の丸め誤差により起こる問題です。

the text "kth_ignore_same_point"  × -> "ignore_kth_same_point" ○

**Comment by rimms** [comment]
Fixed via #344
