### ISSUE TITLE
Fix anomaly tutorial

### ISSUE THREAD

**Issue by hido** [jubatus/website#72]
Explanations for jubaanomaly (LOF) and its results are incorrect.

Need to correct it and update the tutorial source code for all languages.

**Comment by kmaehashi** [comment]
> Need to correct it and update the tutorial source code for all languages.

I'm partially working on this in #180 and #182

**Comment by rimms** [comment]
We renewed our website in 2016. See https://github.com/jubatus/website/issues/283.
This issue was fixed at that time.
